$[ theory/kore.mm $]

${
    $d X xX $.
    $d X ph0 $.
    $d X ph1 $.
    fresh-in-kore-always.0 $e #Fresh xX ph0 $.
    fresh-in-kore-always.1 $e #Fresh xX ph1 $.
    fresh-in-kore-always   $p #Fresh xX ( \kore-always ph0 ph1 ) $=
        $(
            apply "notation-fresh"
            meh
            apply "kore-always-is-sugar", X = "X"
            fresh
        $)
      ( not-is-pattern and-is-pattern or-is-pattern bot-is-pattern not-is-sugar
      imp-is-pattern negative-in-imp notation-reflexivity notation-transitivity
      notation-negative positive-in-imp or-is-sugar fresh-in-imp notation-fresh
      notation-positive set-var-is-var kore-not-is-pattern kore-next-is-pattern
      kore-and-is-pattern negative-disjoint symbol-is-pattern positive-disjoint
      var-is-pattern kore-all-path-next-is-pattern positive-in-var and-is-sugar
      kore-top-is-pattern kore-next-is-symbol kore-not-is-sugar positive-in-app
      X-is-element-var app-is-pattern kore-next-is-sugar kore-always-is-pattern
      kore-all-path-next-is-sugar kore-mu-is-pattern mu-is-pattern fresh-in-app
      kore-and-is-sugar inhabitant-is-symbol kore-top-is-sugar kore-mu-is-sugar
      inh-is-pattern fresh-disjoint inh-is-sugar kore-always-is-sugar
      fresh-in-mu ) AAAABAAUPUAZUHZUBZUIZUDZUBZUPVQFZAULZGZVRVMVSFZVTFZHZFZWAVM
      WDIKZWEVMWDIVMWBFZWCKZWDVMWGWCVMWBIKZWGVMWBIVMVSIKZWBVMVSIVMVQIKZVSVMVQIV
      MBVPGZVQVMBFZVPFZHZFZWLVMWOIKZWPVMWOIVMWMFZWNKZWOVMWRWNVMWRVMUEVPIKZWNVMV
      PIVMAAAVOUBZUCZUBZVPVMXBFZVTGZXCVMXDFZWCHZFZXEVMXGIKZXHVMXGIVMXFFZWCKZXGV
      MXJWCVMXFIKZXJVMXFIVMXDIKZXFVMXDIVMXBIKZXDVMXBIVMUMUFZXAUQZXBVMXOXAVMXOVM
      UGVOFZVTGZXAVMXQFZWCHZFZXRVMXTIKZYAVMXTIVMXSFZWCKZXTVMYCWCVMXSIKZYCVMXSIV
      MXQIKZXSVMXQIVMVOIKZXQVMVOIVMVNFZVTGZVOVMYHFZWCHZFZYIVMYKIKZYLVMYKIVMYJFZ
      WCKZYKVMYNWCVMYJIKZYNVMYJIVMYHIKZYJVMYHIVMVNIKZYHVMVNIVMVMVMUJIVMUEZLYHYR
      YRVNJYRMNOIVMUGZPYJYQYQYHJYQMNTYSLYNYPYPYJJYPMNOWCVMUGZPYKYOYOYJWCQZYOMNT
      YSLYLYMYMYKJZYMMNOYIYLYLYHVTUKZYLMNOVOYIYIAVNUNZYIMNOYTPXQYGYGVOJZYGMNTYS
      LXSYFYFXQJZYFMNOYTPYCYEYEXSJZYEMNTWCVMUEZLXTYDYDXSWCQZYDMNOYTPYAYBYBXTJZY
      BMNTXRYAYAXQVTUKZYAMNTXAXRXRAVOUNZXRMNTUOXBXPXPAXAURZXPMNTYSLXDXNXNXBJZXN
      MNOYTPXFXMXMXDJZXMMNTYSLXJXLXLXFJZXLMNOUUAPXGXKXKXFWCQZXKMNTYSLXHXIXIXGJZ
      XIMNOXEXHXHXDVTUKZXHMNOXCXEXEAXBUNZXEMNOVPXCXCAVOUTZXCMNOYTPWNWTWTVPJZWTM
      NTPWOWSWSWMWNQZWSMNTYSLWPWQWQWOJZWQMNOWLWPWPBVPUKZWPMNOVQWLWLABVPVDZWLMNO
      YTPVSWKWKVQJZWKMNTYSLWBWJWJVSJZWJMNOYTPWGWIWIWBJZWIMNTUUILWDWHWHWBWCQZWHM
      NOYTPWEWFWFWDJZWFMNTWAWEWEVSVTUKZWEMNTVRWAWAAVQUNZWAMNTZVAZUBZABUSCUVPFZV
      TGZUVQCUVRFZWCHZFZUVSCUWAIKZUWBCUWAICUVTFZWCKZUWACUWDWCCUVTIKZUWDCUVTICUV
      RIKZUVTCUVRICUVPIKZUVRCUVPICVRUPUVOVBZAVHZGZUVPCUWIFZUWJFZHZFZUWKCUWNIKZU
      WOCUWNICUWLFZUWMKZUWNCUWQUWMCUWLIKZUWQCUWLICUWIIKZUWLCUWIICVRUPCWAVRCWEWA
      CWFWECWDICWHWDCWGWCCWIWGCWBICWJWBCVSICWKVSCVQICWLVQCWPWLCWQWPCWOICWSWOCWR
      WNCWMIKZWRCWMICBIKZWMCBICEICVIZRWMUXBUXBBJUXBMNSUXCRWRUXAUXAWMJUXAMNSWTWN
      CVPICXCVPCXEXCCXHXECXIXHCXGICXKXGCXJWCCXLXJCXFICXMXFCXDICXNXDCXBICXPXBCXO
      XACXOCVIXRXACYAXRCYBYACXTICYDXTCYCWCCYEYCCXSICYFXSCXQICYGXQCVOICYIVOCYLYI
      CYMYLCYKICYOYKCYNWCCYNCVIVTIKZWCCVTICUWJVTCVEUFZAUQZUWJCUXEACUXECVIDVCUWJ
      UXFUXFAVJUXFMNSZVTUWJUWJAVFUWJMNSUXCRWCUXDUXDVTJUXDMNSZRUUBSUXCRUUCSUUDSU
      UESUXCRUUFSUXCRUUGSUXCRUUHSUXHRUUJSUXCRUUKSUULSUUMSVCUUNSUXCRUUOSUXCRUUPS
      UXCRUUQSUXHRUURSUXCRUUSSUUTSUVASUVBSUXCRUVCSRUVDSUXCRUVESUVFSUVGSUXCRUVHS
      UXCRUVISUXCRUVJSUXHRUVKSUXCRUVLSUVMSUVNSVLUXCRUWLUWTUWTUWIJUWTMNSUXCRUWQU
      WSUWSUWLJUWSMNSUWJIKZUWMCUWJICUXGUXCRUWMUXIUXIUWJJUXIMNSRUWNUWRUWRUWLUWMQ
      UWRMNSUXCRUWOUWPUWPUWNJUWPMNSUWKUWOUWOUWIUWJUKUWOMNSUVPUWKUWKAVRUPVGUWKMN
      SUXCRUVRUWHUWHUVPJUWHMNSUXCRUVTUWGUWGUVRJUWGMNSUXCRUWDUWFUWFUVTJUWFMNSUXH
      RUWAUWEUWEUVTWCQUWEMNSUXCRUWBUWCUWCUWAJUWCMNSUVSUWBUWBUVRVTUKUWBMNSUVQUVS
      UVSAUVPUNUVSMNSABUPVKS $.
$}

${
    $d X xX $.
    $d X ph0 $.
    $d X ph1 $.
    fresh-in-kore-circularity.0 $e #Fresh xX ph0 $.
    fresh-in-kore-circularity.1 $e #Fresh xX ph1 $.
    fresh-in-kore-circularity   $p #Fresh xX ( \kore-circularity ph0 ph1 ) $=
        $( fresh $)
        ( not-is-pattern kore-always-is-pattern kore-not-is-pattern kore-top-is-pattern kore-next-is-pattern bot-is-pattern imp-is-pattern or-is-pattern notation-reflexivity notation-transitivity notation-fresh symbol-is-pattern fresh-disjoint and-is-pattern app-is-pattern fresh-in-imp inh-is-pattern inhabitant-is-symbol not-is-sugar kore-all-path-next-is-pattern kore-next-is-symbol fresh-in-app kore-circularity-is-pattern inh-is-sugar kore-top-is-sugar or-is-sugar and-is-sugar kore-not-is-sugar fresh-in-kore-always kore-next-is-sugar kore-all-path-next-is-sugar kore-circularity-is-sugar ) AABGUEABUHCAAAABGHJHAABGUECAAABGHJFAISAAAABGHJHCAAABGHJFFAIFMFAAABGHJFAISCAAABGHJFFAIFMKLAAABGHJFFAIFMFCAAABGHJFFAIFMKCAAABGHJFFFAIFLAAABGHJFFAIFMCAAABGHJFFFAIFCAAABGHJFFKLAAABGHJFFFCAAABGHJFFKCAAABGHJFKLAAABGHJFFCAAABGHJFKCAAABGHJKLAAABGHJFCAAABGHJKCUFQAABGHTAAABGHJCUFQAABGHCUFQCRABGFAISAABGHCABGFFAIFMFABGFAISCABGFFAIFMKLABGFFAIFMFCABGFFAIFMKCABGFFFAIFLABGFFAIFMCABGFFFAIFCABGFFKLABGFFFCABGFFKCABGFKLABGFFCABGFKCABGKLABGFCABGKCABCDEUNKCRUAABGFABGKLABGKLABGUDABGKLNOPKCRUAABGFFABGFKLABGFKLABGFUDABGFKLNOPKCRUAABGFFFABGFFKLABGFFKLABGFFUDABGFFKLNOPAIKLAIFCAIKCAUBAICUCQATAUBCUCQACUCQCRDUGAUBUCQATUCQATAUIUCQATNOPAIAUBAUBAUJAUBNOPKCRUAAIFAIKLAIKLAIUDAIKLNOPUAABGFFAIFMABGFFFAIFLABGFFFAIFLABGFFAIFUKABGFFFAIFLNOPKCRUAABGFFAIFMFABGFFAIFMKLABGFFAIFMKLABGFFAIFMUDABGFFAIFMKLNOPABGFAISABGFFAIFMFABGFFAIFMFABGFAIULABGFFAIFMFNOPAABGHABGFAISABGFAISAABGUMABGFAISNOPUGAAABGHJUFQAABGHTUFQAABGHTAAABGHUOUFQAABGHTNOPKCRUAAAABGHJFAAABGHJKLAAABGHJKLAAABGHJUDAAABGHJKLNOPKCRUAAAABGHJFFAAABGHJFKLAAABGHJFKLAAABGHJFUDAAABGHJFKLNOPKCRUAAAABGHJFFFAAABGHJFFKLAAABGHJFFKLAAABGHJFFUDAAABGHJFFKLNOPAIKLAIFCAIKCAUBAICUCQATAUBCUCQACUCQCRDUGAUBUCQATUCQATAUIUCQATNOPAIAUBAUBAUJAUBNOPKCRUAAIFAIKLAIKLAIUDAIKLNOPUAAAABGHJFFAIFMAAABGHJFFFAIFLAAABGHJFFFAIFLAAABGHJFFAIFUKAAABGHJFFFAIFLNOPKCRUAAAABGHJFFAIFMFAAABGHJFFAIFMKLAAABGHJFFAIFMKLAAABGHJFFAIFMUDAAABGHJFFAIFMKLNOPAAABGHJFAISAAABGHJFFAIFMFAAABGHJFFAIFMFAAABGHJFAIULAAABGHJFFAIFMFNOPAAAABGHJHAAABGHJFAISAAABGHJFAISAAAABGHJUMAAABGHJFAISNOPAABGUEAAAABGHJHAAAABGHJHAABGUPAAAABGHJHNOPABUHAABGUEAABGUEABUQAABGUENOP $.
$}
