#!/usr/bin/env bash

set -euo pipefail

# Dependencies
# ============

build-metamath() {
    (   git submodule update --init --recursive deps/metamath-exe/
        cd deps/metamath-exe/src
        gcc m*.c -o metamath
    )
    PATH="$(pwd)/deps/metamath-exe/src:$PATH"
}

build-k() {
    (   git submodule update --init --recursive deps/k/
        cd deps/k
        mvn package -DskipTests -Dllvm.backend.skip
    )
    PATH="$(pwd)/deps/k/k-distribution/bin/:$PATH"
}

# Tests
# =====

static-checks() {
    yapf --recursive --diff ml scripts tests
    mypy --strict --no-incremental ml scripts tests
}

unit-tests() {
    pytest "$@" --ignore=deps
}

metamath-verify() {
    # Modified from https://github.com/metamath/set.mm/blob/develop/scripts/verify
    # We should find a cleaner way of doing this long term.
    mmfile=$1; shift
    log_file=.build/${mmfile}.log
    echo "Checking '$mmfile'"
    mkdir -p $(dirname "$log_file")
    metamath > "$log_file" << COMMANDS
set echo on
set scroll continuous
read '${mmfile}'
verify proof *
quit
COMMANDS
    # Get status, which is false (nonzero) if an error or warning was found.
    ! grep -E '[?]Error|[?]Warning' < "$log_file" > /dev/null || {
        echo "FAILED. See: $log_file";
        return 1;
    }
}

metamath-verify-all() {
    for f in "$@"; do
        metamath-verify "$f"
    done
}

kore-to-metamath() {
    kore_file=$1; shift
    main_module=$1; shift
    output=$1; shift
    python -m ml.rewrite --standalone --prelude theory/prelude.mm \
           "$kore_file" "$main_module" -o "$output"
}

test-kompile-and-verify() {
    example_name=$1; shift
    main_module=$1; shift
    kompile --backend haskell "examples/${example_name}/${example_name}.k" --directory ".build/${example_name}/"
    kore-to-metamath ".build/${example_name}/${example_name}-kompiled/definition.kore" "${main_module}" ".build/${example_name}/definition.mm"
    metamath-verify ".build/${example_name}/definition.mm"
}

static-checks
unit-tests
build-metamath
metamath-verify-all theory/matching-logic*.mm theory/prelude.mm
build-k
test-kompile-and-verify imp IMP
