#!/usr/bin/env bash

set -euo pipefail

mypy --show-column-numbers --strict ml/pml
export PYTHONHASHSEED=1 # Avoid non-deterministic issues with sets.
                        # It might make sense to test with a few different seeds
echo $PYTHONHASHSEED
pytest "$@"
